### ISSUE TITLE
Investigation for Optimization and Refactoring of Code to Standards

### ISSUE THREAD

**Issue by 1601** [1601/gatsby-netlify-cms-sho#18]
Investigate and apply a code quality third party

**Comment by erangot** [comment]
Sho.co forked from 1601

![image](https://user-images.githubusercontent.com/30464172/59750206-027b1c00-92b1-11e9-8d9a-e2e53be2a81b.png)

**Comment by 1601** [comment]
Copy on this Ivy. Thank you for implementing.

**Comment by 1601** [comment]
Hi @erangot , are there suggestions? more data to help us rank better. 
Can we access the code climate you have it in?

**Comment by erangot** [comment]
Hi @1601 since it's been set to public now, you can add your repository to code climate
Here are also still a list of alternatives we can further check out, I will look into this as well: https://stackshare.io/code-climate/alternatives
I think the results can be viewed if you forked it or you're the repo owner, after creating an account in code climate using your github

**Comment by 1601** [comment]
Released on release/0.1
